"""add extra fields to loan

Revision ID: e293bdce5822
Revises: 4898877669ee
Create Date: 2025-12-04 08:16:22.627284

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op

# Primero lo definimos y luego le decimos que la agregue para así evitar error al hacer upgrade y downgrade
loan_status_enum = sa.Enum(
    "ACTIVE",
    "RETURNED",
    "OVERDUE",
    name="loan_status_enum",
)


# revision identifiers, used by Alembic.
revision: str = 'e293bdce5822'
down_revision: Union[str, Sequence[str], None] = '4898877669ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


   
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el tipo ENUM en la BD si no existe
    bind = op.get_bind()
    loan_status_enum.create(bind, checkfirst=True)

    # due_date: NOT NULL con default para filas viejas
    op.add_column("loans",sa.Column("due_date",sa.Date(),nullable=False,server_default=sa.text("CURRENT_DATE")))

    # fine_amount: Decimal(10, 2)
    op.add_column("loans",sa.Column("fine_amount",sa.Numeric(10, 2),nullable=True))

    # status: ENUM con default ACTIVE
    op.add_column("loans",sa.Column("status",loan_status_enum,nullable=False,server_default="ACTIVE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_date')
    # ### end Alembic commands ###

    # Eliminar el tipo enum de la BD
    bind = op.get_bind()
    loan_status_enum.drop(bind, checkfirst=True)
